import { LlmProvider } from "./LlmProvider";
import { CrmRecord } from "@groweasy/shared";

/** * Deterministic, network-free stand-in for GeminiProvider (ADR-004 
 * benefit in action: swapping providers touches only this file's 
 * peer, nothing in services/ or controllers/). 
 * * Use via env flag (LLM_PROVIDER=mock) so SSE plumbing, batching, 
 * job state transitions, and the results UI can all be tested 
 * end-to-end before real Gemini integration lands in Phase 3. 
 * * Simulates realistic behavior: 
 * - Small artificial delay per batch (mimics network latency) 
 * - One row per batch deliberately returns a bad enum, to exercise 
 * the needs_review path through validationService 
 */
export class MockProvider implements LlmProvider {
  constructor(private simulatedDelayMs: number = 300) {}
  
  async extractRecords(
    rows: Record<string, string>[]
  ): Promise<Partial<CrmRecord>[]> {
    await new Promise((resolve) => setTimeout(resolve, this.simulatedDelayMs));
    
    return rows.map((raw, i) => {
      const row_index = Number(raw["__row_index"] ?? i);
      
      // Seed one intentionally-invalid record per batch (index 0) 
      // so needs_review is exercised without needing real bad data. 
      if (i === 0 && rows.length > 1) {
        return {
          row_index,
          crm_status: "NOT_A_REAL_STATUS" as any, // deliberately invalid 
          created_at: null,
          name: raw["name"] ?? raw["Name"] ?? null,
          email: raw["email"] ?? raw["Email"] ?? null,
          data_source: null,
        };
      }
      
      return {
        row_index,
        created_at: new Date().toISOString(),
        name: raw["name"] ?? raw["Name"] ?? "Mock Name",
        email: raw["email"] ?? raw["Email"] ?? "mock@example.com",
        country_code: "+91",
        mobile_without_country_code: raw["mobile"] ?? "9999999999",
        company: null,
        city: null,
        state: null,
        country: "India",
        lead_owner: null,
        crm_status: "GOOD_LEAD_FOLLOW_UP",
        crm_note: "Generated by MockProvider — not real AI output",
        data_source: "leads_on_demand",
        possession_time: null,
        description: null,
      };
    });
  }
}
