import { LlmProvider } from "./LlmProvider";
import { CrmRecord } from "@groweasy/shared";
import { IndexedRow } from "../utils/csvStreamParser";
import { detectColumnsNaive } from "../utils/csvStreamParser";
import { ColumnDetectionResult } from "./LlmProvider";

export class MockProvider implements LlmProvider {
  constructor(private simulatedDelayMs: number = 300) {}
  async detectContactColumns(headers: string[]): Promise<ColumnDetectionResult> {
    await new Promise((resolve) => setTimeout(resolve, this.simulatedDelayMs));
    return detectColumnsNaive(headers);
  }
  async extractRecords(rows: IndexedRow[]): Promise<Partial<CrmRecord>[]> {
    await new Promise((resolve) => setTimeout(resolve, this.simulatedDelayMs));
    
    return rows.map(({ row_index, raw }, i) => {
      // Seed one intentionally-invalid record per multi-row batch so
      // validationService's needs_review path gets exercised.
      if (i === 0 && rows.length > 1) {
        return {
          row_index,
          crm_status: "NOT_A_REAL_STATUS" as any, // deliberately invalid
          created_at: null,
          name: raw["name"] ?? raw["Name"] ?? null,
          email: raw["email"] ?? raw["Email"] ?? null,
          data_source: null,
        };
      }
      
      return {
        row_index,
        created_at: new Date().toISOString(),
        name: raw["name"] ?? raw["Name"] ?? "Mock Name",
        email: raw["email"] ?? raw["Email"] ?? "mock@example.com",
        country_code: "+91",
        mobile_without_country_code: raw["mobile"] ?? "9999999999",
        company: null,
        city: null,
        state: null,
        country: "India",
        lead_owner: null,
        crm_status: "GOOD_LEAD_FOLLOW_UP",
        crm_note: "Generated by MockProvider — not real AI output",
        data_source: "leads_on_demand",
        possession_time: null,
        description: null,
      };
    });
  }
}